name: picto_parlant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.6.3
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Pictogramas/Acciones/
    - assets/Pictogramas/Carnes/
    - assets/Pictogramas/Cocina/
    - assets/Pictogramas/Deportes_juegos/
    - assets/Pictogramas/Estado/
    - assets/Pictogramas/Estudios/
    - assets/Pictogramas/Lugares/
    - assets/Pictogramas/Objetos/
    - assets/Pictogramas/Postres/
    - assets/Pictogramas/Ropa/
    - assets/Pictogramas/Varios/
    - assets/Pictogramas/Vegetales_frutas/
